### ISSUE TITLE
Build template for search results

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#15]
1. One is located in menu bar, and another (large search bar) is located on home page. We just need one, I'd suggest we keep one in menu bar.

**Comment by ewels** [comment]
Why do we need just one?

**Comment by ewels** [comment]
My logic is that we want one in the nav bar so that it is always present. Because the website has so much content, navigation is always going to be challenging. By adding a big search bar underneath the applications / technologies, users are naturally directed on to there if they don't see what they are looking for in the categories.

**Comment by Nazeeefa** [comment]
I understand. Perhaps we can come back to this (large search bar) once we are at the stage of polishing home page. It is useful though.

**Comment by Nazeeefa** [comment]
About the one in nav bar, is it possible to make sure that it hides (_rolls back_) upon click on search icon? Because, apparently, it does hide but only when you click on empty space/area around it.

**Comment by Nazeeefa** [comment]
2. Typing in search bar and hitting enter without delay takes user to the (page of) first/all hit(s) from the list, rather than displaying results in drop-down (and allowing user to choose where to go next).

**Comment by ewels** [comment]
Is this not the expected behaviour? This is how I usually use the search bar - start typing, scroll down through the options, hit enter..

**Comment by Nazeeefa** [comment]
> Is this not the expected behaviour? This is how I usually use the search bar - start typing, scroll down through the options, hit enter..

Yeah, no & except it doesn't let user scroll down through options. You can test and see what I mean.

**Comment by ewels** [comment]
Yes it does? Example:

![Feb-22-2020 11-19-59](https://user-images.githubusercontent.com/465550/75090699-d6154f00-5565-11ea-9e17-2903e40ff274.gif)

**Comment by ewels** [comment]
I think this may be confusion due to the fact that the `search.php` template doesn't exist yet and is defaulting to `index.php`, which shows the full post output for all posts on the page.

For example, the search results page for `rna`: https://ngisweden-dev.scilifelab.se/?s=rna - if you scroll down then you'll see the full page for every search result that contains the term `rna` (not just the first result).

I actually noticed the same thing last week (in fact I mentioned it in https://github.com/NationalGenomicsInfrastructure/ngisweden.se/issues/22#issuecomment-589923684) - I will make a proper search results template which I think should resolve this.

**Comment by ewels** [comment]
Written 👍 

![image](https://user-images.githubusercontent.com/465550/78360773-99526400-75b7-11ea-87b1-5c748f35adeb.png)
