### ISSUE TITLE
Sitemap List

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#17]
There seems to be two types of pages, ones with IDs are taken from the sitemap list.

**Example (A):** 
1. https://ngisweden-dev.scilifelab.se/applications/single-cell/
2. Page with ID tag https://ngisweden-dev.scilifelab.se/?page_id=2447

**Example (B):**
1. https://ngisweden-dev.scilifelab.se/applications/de-novo/
2. Page with ID tag https://ngisweden-dev.scilifelab.se/?page_id=442

Posting it here because there was confusion regarding which one to work on.

**Comment by ewels** [comment]
This is due to page status - if it's a draft it will have an ID, once published it will have a nice name (the "slug" for the page). Applications are categories instead of posts so don't have a published or draft status, so they always get nice URLs.

In short - all will have nice descriptive URLs once written 👍
