### ISSUE TITLE
Click action on search icon in nav bar

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#18]
1. Is it possible to make sure that it hides (_rolls back_) upon click on search icon? Because, apparently, it does hide but only when you click on empty space/area around it.

2. Hitting enter in empty search bar(s) lead to https://ngisweden-dev.scilifelab.se/?s=

**Comment by ewels** [comment]
Now done I think.. It doesn't hide when you click the search icon, but it doesn't launch the search page either (and it hides if you click anywhere else).

Hitting enter now gives a full search page which is better functionality / more as expected.

If an empty string is given, the search page now shoes no results instead of all content on the website.
