### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#19]
Ideally, clicking on _ABOUT US_ tab in nav bar should take user to About us page. Rather than requiring another click to view about us page. Therefore, it is not required in the drop-down list.

![Screenshot from 2020-02-13 16-40-42](https://user-images.githubusercontent.com/6730853/74452253-1d725000-4e81-11ea-9d02-6f23c7f48238.png)

Alternatively, we can replace the name with "Who We Are" in drop-down list.

**Comment by ewels** [comment]
If you do right click > open in new tab on it then I think it already opens that page.

However, because it's a drop down item and not a link then clicking will only ever handle the drop down event. It should not also be a link sorry.

I think this is a fairly minor issue as the "About us" page will probably get very little traffic :)
