### ISSUE TITLE
Style News archive page

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#22]
Instead of having multiple sub-pages for each news (or even events) given that information is not too much, it would be better to have two carousels**, one for news and one for events on same page.

Something like this (example):
![carousel](https://user-images.githubusercontent.com/6730853/74936498-88c0a280-53ea-11ea-93e7-84d3a16dfa25.png)

Plugin: https://wordpress.org/plugins/wp-carousel-free/ (in case we need this too although we have Bootstrap Carousel that is also fine as long as it allows post and not just image-based carousels).

**Suggestion: we could also add one more and name it "In Press" and that's where we can add links (with video thumbnails or images) to related/our content published on other websites.

**Comment by ewels** [comment]
Yup - I haven't done anything for styling News yet, or Search results. Needs looking at.

Personally I would prefer not to use carousels as I don't like hiding content. But nicer visuals and making it easier to skim is definitely warranted.

**Comment by Nazeeefa** [comment]
Interesting. I don't view carousels as hiding content, they remind me more of digital screens except better as it user can interact with it xD but maybe that's just me. Do let me know what you have in mind in terms of visual design/styling 😊 Cheers!

**Comment by ewels** [comment]
They work well on digital screens and homepages because they are passive and eye catching. If someone visits our news page then the intent is a little different - they will want to actively scan over the available articles. With a carousel they will have to wait / click to move through the articles. This extra step is a barrier, and will be particularly annoying if the user is looking for something specific.

The first layout option that jumps to mind is some kind of "masonry" blocks, eg. using bootstrap card coloumns: https://getbootstrap.com/docs/4.4/components/card/#card-columns

I'll mock something up next week.

**Comment by Nazeeefa** [comment]
or we could try this out https://www.ultimategutenberg.com/docs/post-masonry/ :smiley_cat:

**Comment by ewels** [comment]
Wrote template pages for search and news results.

Have just done a simple list for now. Can look into a masonry layout.

**Comment by ewels** [comment]
ok I had a quick play with a masonry layout and it looks pretty cool. No need for plugins 😉 

![image](https://user-images.githubusercontent.com/465550/78361249-6197ec00-75b8-11ea-9d99-8cdda31ba162.png)

For News, I have made it similar-but-different: 

![image](https://user-images.githubusercontent.com/465550/78362192-fc44fa80-75b9-11ea-9b37-315e983cb146.png)


This is because masonry orders content top-bottom, then left-right. For the search this doesn't matter much as the order of results isn't super important. But for the news it's a bit confusing as you can't read left-right to get things in date order.

So instead I've just done a regular card grid, which works as you'd expect and still looks pretty good I think.

**Comment by ewels** [comment]
Deployed.
