### ISSUE TITLE
Carousel (Home Page)

### ISSUE THREAD

**Issue by Nazeeefa** [NationalGenomicsInfrastructure/ngisweden.se#28]
Here are some suggestions:

**1.** Clear/visible (arrow) navigation for user to know there is more than one slide.

**2.** Translucent text box (as the one you showed in example) with dark-coloured font.

**3.** Move Latest News text and links to carousel slides; given that one purpose of having carousel is to encourage users to further visit the website. Latest News bit is more likely to be missed (given its location on page) as compared to carousel. Yes, this will require update (e.g. when there are latest updates) however it creates good impression at first visit and makes content look organised.

**4.** We should keep number of slides below 5 (currently, there are over 10 slides).

**5.** Add link to first slide as well (e.g. Read More / Find out more) that takes user to either 'About Us' or 'Getting Started..' page.

**6.** We should resize carousel so that search bar and three categories (Applications/../..) are visible on first sight.

That's all for now. Tbh, the more I spend time thinking about this, the more I want to avoid carousel 😂 Anyway, hope the suggestions help.

**Comment by ewels** [comment]
I guess you wrote this issue whilst I was working on the new carousel 😄 As basically all of these are done as of about an hour ago.

The only one I don't want to do is moving the news. The news articles are generally less important than the carousel items, which will typically be new methods and techniques that we want to draw attention to. This is a different type of content to news articles.

I think I had already done all other points before reading this (I switched the link on the first slide to your suggestion instead of "new order", better idea), but let me know if there is anything else.

**Comment by Nazeeefa** [comment]
It looks great! Thank you! ☺️ I also like the addition of bars across the bottom.

I think the remaining point is 6, and I was wondering if it is possible to reduce/crop size from bottom? unless that doesn't look so good then forget it xD

If latest news is not so important then it seems it's consuming space (more than it should) and adds more to scrolling.

**Comment by ewels** [comment]
You mean make the carousel shorter? I don’t think that would work as there would be very little room for content then. The concept of “Below the fold” is getting less popular in web design over the past years because people are viewing on such a range of devices. Plus people are a lot more used to scrolling than they were a decade ago (the term and concept came from newspaper design).

I’m happy with the current layout of content too, regarding the news. At the moment the homepage follows the priority of content pretty well. We highlight the top things that we want everyone to know about in the carousel. This is followed by our services which is what most people will be looking for. News items are next, followed by other updates and how to stay involved. I think it’s quite a natural flow..

**Comment by Nazeeefa** [comment]
I am also happy with flow and content. I was just worried about blank spaces in latest news area and towards the bottom of page (before footer). Otherwise, I think we have a great home page! Thank you!
